import http from 'node:http'; import fs from 'node:fs'; import path from 'node:path'; import { chromium } from '@playwright/test';
const DIST=path.resolve('dist'); const OUT=process.env.OUT||'/tmp/claude-0/-home-user/d2c27694-77fe-50f8-b585-babc4fe7735f/scratchpad/shots'; fs.mkdirSync(OUT,{recursive:true});
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.png':'image/png','.jpg':'image/jpeg','.svg':'image/svg+xml','.glb':'model/gltf-binary','.mp4':'video/mp4','.wav':'audio/wav','.mp3':'audio/mpeg','.ico':'image/x-icon','.woff2':'font/woff2','.ktx2':'application/octet-stream','.bin':'application/octet-stream'};
const server=http.createServer((req,res)=>{let p=decodeURIComponent(req.url.split('?')[0]); if(p==='/'||p==='')p='/index.html'; let fp=path.join(DIST,p); if(!fp.startsWith(DIST)){res.writeHead(403);return res.end();} fs.readFile(fp,(e,d)=>{if(e){res.writeHead(404);return res.end('nf');} res.writeHead(200,{'Content-Type':MIME[path.extname(fp)]||'application/octet-stream'});res.end(d);});});
await new Promise(r=>server.listen(8099,r));
const VW=Number(process.env.VW||1280), VH=Number(process.env.VH||720);
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome'}); const pg=await b.newPage({viewport:{width:VW,height:VH}}); pg.on('pageerror',e=>console.log('ERR',e.message.split('\n')[0]));
for(const s of process.argv.slice(2)){const [c,h,cam]=s.split(':'); const u=`${process.env.BASE||"http://localhost:8099"}/?ff.courseRebuilds=on&ff.newCourses=on${process.env.EXTRA||""}&course=${c}&hole=${h}&cam=${cam}&freeze=1`; try{await pg.goto(u,{waitUntil:'domcontentloaded',timeout:60000}); await pg.waitForFunction('window.__shotReady===true',null,{timeout:90000,polling:400}); await pg.waitForTimeout(1200); const d=await pg.evaluate(()=>document.querySelector('canvas').toDataURL('image/png')); fs.writeFileSync(`${OUT}/${c}_h${h}_${cam}.png`,Buffer.from(d.replace(/^data:image\/png;base64,/,''),'base64')); console.log('OK',s);}catch(e){console.log('FAIL',s,e.message.split('\n')[0]);}}
await b.close(); server.close();
