/**
 * Pals — companion pets that follow the player around the course and settle
 * off to the side of the ball while they hit. Purely decorative: no gameplay
 * effect, so nothing outside the renderer ever branches on which pal is
 * equipped. Models are the uploaded pets converted by scripts/convert-pals.mjs
 * into assets/models/pals/.
 *
 * The starter pair is free and owned by default; future pals arrive as priced
 * `pal` items in the store catalog.
 */
export type PalKey =
  | 'fox'
  | 'dragon'
  | 'gecko'
  | 'trex'
  | 'crab'
  | 'pug'
  | 'cat'
  | 'foxorange'
  | 'geckoorange'
  | 'trice'
  | 'toothless'
  | 'deadpool'
  | 'spidey';

export interface PalDef {
  key: PalKey;
  /** Label shown on the Pals screen and store cards. */
  name: string;
  /** glb path, relative (no leading slash) for the GitHub Pages subpath. */
  file: string;
  /** World-unit height the model is normalized to (golfers stand 5.2). */
  targetHeight: number;
  /** Emoji stand-in shown on compact menu cards. */
  icon: string;
  /** Rendered portrait PNG, relative path (no leading slash). Generated by
   *  `npm run pal-portraits` into assets/ui/pals/<key>.png; used for the
   *  full-render Season-Pass hero cards. */
  image: string;
}

const def = (key: PalKey, name: string, targetHeight: number, icon: string): PalDef => ({
  key,
  name,
  file: `models/pals/${key}.glb`,
  targetHeight,
  icon,
  image: `ui/pals/${key}.png`
});

// Sizes bumped +50% (playtest — pals read too small next to the golfer): fox
// 2.4 -> 3.6, dragon 3.0 -> 4.5 (golfers stand 5.2). setSizeMult keeps the
// putting-view shrink proportional. Gecko/trex/crab sized the same way —
// low-slung critters shorter, the trex the tallest pal in the roster.
export const PALS: PalDef[] = [
  def('fox', 'Foxy', 3.6, '🦊'),
  def('dragon', 'Ember', 4.5, '🐉'),
  def('gecko', 'Zippy', 2.6, '🦎'),
  def('trex', 'Rexy', 6.2, '🦖'),
  def('crab', 'Clawdia', 3.1, '🦀'),
  // Pugsley bumped again 2.6 -> 3.4 (owner request: ~1.3x — the pug still read
  // small next to the golfer even after the roster-wide +50% pass).
  def('pug', 'Pugsley', 3.4, '🐶'),
  def('cat', 'Whiskers', 2.9, '🐱'),
  // A warm red-fox recolor of the arctic fox (same mesh, coat re-chroma'd to
  // orange at convert time → its own foxorange.glb) — a second fox option
  // alongside the original, not a replacement.
  def('foxorange', 'Rusty', 3.6, '🦊'),
  // Bright-orange gecko recolor (same mesh as Zippy) — a Season 1 pass
  // exclusive; never sold in the store.
  def('geckoorange', 'Mango', 2.6, '🦎'),
  // Season 1 pass marquee companions (levels 46-50, pass-exclusive). Static
  // uploaded chibi models converted by convert-pals; sized like the other
  // critters (low-slung dino, taller humanoids, dragon as tall as Ember).
  def('trice', 'Triceratops', 3.4, '🦕'),
  def('toothless', 'Toothless', 4.5, '🐉'),
  def('deadpool', 'Deadpool', 4.6, '🗡️'),
  def('spidey', 'Spiderman', 4.6, '🕷️')
];

export function palByKey(key: string | undefined): PalDef | undefined {
  return PALS.find((p) => p.key === key);
}
